# Generated by Django 3.2.3 on 2021-05-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='if_rent',
        ),
    ]
